name: vchatz
description: "A new Flutter project."

# This app is not published to pub.dev
publish_to: 'none'

# App version: major.minor+build
version: 1.0.0+1

environment:
  # Dart SDK version required
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter  # Flutter SDK

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # For State Management
  get: ^4.7.2

dev_dependencies:
  # For writing Flutter tests
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  # Linting rules for good code style
  flutter_lints: ^5.0.0

flutter:

  # Use Material Design widgets
  uses-material-design: true

  # Add image and other assets here
  assets:
    - images/
